spring.datasource.url=jdbc:postgresql://localhost:5432/devcollab
spring.datasource.username=postgres
spring.datasource.password=postgre123

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true